### PR TITLE
Fix converge and some stuff

### PR DESCRIPTION
**Pull request by 8la**
* Suite names on tavis yml
* Yum scl repo
* Fix Vbox no audio
* Fix username for autocreate db data when testing.

### CODE REVIEW

**Comment by 8la** [comment]
centos7 is fixed  that is what we use. Ill try to fix all other platforms.

**Comment by vkhatri** [comment]
@8la Thank you for the PR!

I will release a new version shortly.

**Comment by 8la** [comment]
Im working o integrate actual versions on our environment. Do i have to wait because there will be breaking changes?

**Comment by 8la** [comment]
@vkhatri i would be nice to know a bit about your roadmap because im right now deploying icinga service based on the actual cookbooks. Should i do by hand in order to wait for the new release of the official icinga2 cookbokos?

**Pull request merged**
